[workspace]
members = [
    "mistralrs-server",
    "mistralrs-core",
    "mistralrs-lora",
    "mistralrs-pyo3",
    "mistralrs",
    "mistralrs-bench",
]
resolver = "2"

[workspace.package]
version = "0.1.3"
edition = "2021"
description = "Fast and easy LLM serving."
homepage = "https://github.com/EricLBuehler/mistral.rs"
repository = "https://github.com/EricLBuehler/mistral.rs"
keywords = ["machine-learning"]
categories = ["science"]
license = "MIT"

[workspace.dependencies]
anyhow = { version = "1.0.80", feature = "std" }
candle-core = { git = "https://github.com/EricLBuehler/candle.git", version = "0.5.0" }
candle-nn = { git = "https://github.com/EricLBuehler/candle.git", version = "0.5.0" }
serde = "1.0.197"
serde_json = "1.0.114"
indexmap = { version = "2.2.5", features = ["serde"] }
either = { version = "1.10.0", features = ["serde"] }
accelerate-src = { version = "0.3.2" }
intel-mkl-src = { version = "0.8.1", features = ["mkl-static-lp64-iomp"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
futures = "0.3"
clap = { version = "4.5.1", features = ["derive"] }
pyo3 = { version = "0.21.0", features = ["extension-module", "full"] } # pyo3 = { version = "0.21.0", features = ["extension-module", "full"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }

[profile.profiling]
inherits = "release"
debug = true

[profile.dev]
opt-level = 3
